import { atDay } from "./clock";
import { dmThreadId } from "./chat";
import type { CalendarEvent, Family, Member, Post } from "./types";

export const families: Family[] = [
  {
    id: "alvarez",
    name: "The Alvarez Circle",
    tagline: "Atlanta · three generations · one hearth",
  },
  {
    id: "okonkwo",
    name: "The Okonkwo Circle",
    tagline: "Decatur · opted-in comparison patient",
  },
];

export const members: Member[] = [
  {
    id: "elena",
    familyId: "alvarez",
    name: "Elena Alvarez",
    role: "Abuela",
    age: 78,
    initials: "EA",
    color: "#b45309",
    location: "Grant Park",
    clinicalOptIn: true,
    easyModeDefault: true,
  },
  {
    id: "miguel",
    familyId: "alvarez",
    name: "Miguel Alvarez",
    role: "Son",
    age: 52,
    initials: "MA",
    color: "#9a3412",
    location: "Inman Park",
    clinicalOptIn: false,
  },
  {
    id: "priya",
    familyId: "alvarez",
    name: "Priya Alvarez",
    role: "Daughter-in-law",
    age: 48,
    initials: "PA",
    color: "#7c2d12",
    location: "Inman Park",
    clinicalOptIn: false,
  },
  {
    id: "sofia",
    familyId: "alvarez",
    name: "Sofia Alvarez",
    role: "Granddaughter",
    age: 17,
    initials: "SA",
    color: "#c2410c",
    location: "Grady High",
    clinicalOptIn: false,
  },
  {
    id: "james",
    familyId: "alvarez",
    name: "James Alvarez",
    role: "Grandson (GT)",
    age: 21,
    initials: "JA",
    color: "#92400e",
    location: "Georgia Tech",
    clinicalOptIn: false,
  },
  {
    id: "ruth",
    familyId: "okonkwo",
    name: "Ruth Okonkwo",
    role: "Nana",
    age: 74,
    initials: "RO",
    color: "#0f766e",
    location: "Decatur",
    clinicalOptIn: true,
  },
];

const photoGarden =
  "https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=1200&q=80";
const photoSoccer =
  "https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=1200&q=80";
const photoKitchen =
  "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80";
const photoCampus =
  "https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1200&q=80";

export const posts: Post[] = [
  {
    id: "p1",
    familyId: "alvarez",
    authorId: "elena",
    kind: "text",
    body: "I spent the morning thinning the basil so the tomatoes can breathe. Miguel, the red ones on the south fence are ready if you want to come by Sunday. I put a chair in the shade for Priya.",
    createdAt: atDay(38, 9, 12),
  },
  {
    id: "p2",
    familyId: "alvarez",
    authorId: "sofia",
    kind: "photo",
    body: "First varsity start this Saturday. Abuela you better be loud.",
    photoUrl: photoSoccer,
    photoAlt: "Sofia in a soccer jersey on the field",
    createdAt: atDay(36, 16, 40),
  },
  {
    id: "p3",
    familyId: "alvarez",
    authorId: "elena",
    kind: "voice",
    body: "Voice note",
    transcript:
      "Mija I am so proud of you. I will wear the yellow scarf your grandfather liked. Tell coach I still remember how to yell.",
    voiceSeconds: 18,
    createdAt: atDay(36, 17, 5),
  },
  {
    id: "p4",
    familyId: "alvarez",
    authorId: "james",
    kind: "photo",
    body: "Hackathon fuel. Miss kitchen table energy. Send empanadas via teleport.",
    photoUrl: photoCampus,
    photoAlt: "Georgia Tech campus at dusk",
    createdAt: atDay(34, 22, 10),
  },
  {
    id: "p5",
    familyId: "alvarez",
    authorId: "priya",
    kind: "text",
    body: "Sunday lunch is at our place if the garden run happens. Elena, I'll pick you up at 11 so you don't have to drive.",
    createdAt: atDay(33, 11, 2),
  },
  {
    id: "p6",
    familyId: "alvarez",
    authorId: "elena",
    kind: "text",
    body: "Thank you Priya. I am grateful we still sit down together. I made the salsa the way your mother likes, extra lime.",
    createdAt: atDay(33, 11, 40),
  },
  {
    id: "p7",
    familyId: "alvarez",
    authorId: "miguel",
    kind: "status",
    body: "Dad's old radio is working again. Putting it on the porch for the game.",
    createdAt: atDay(28, 19, 15),
  },
  {
    id: "p8",
    familyId: "alvarez",
    authorId: "elena",
    kind: "photo",
    body: "Harvest day. These tomatoes waited all summer. I want everyone to take a bag.",
    photoUrl: photoGarden,
    photoAlt: "Ripe tomatoes on a vine",
    createdAt: atDay(27, 8, 50),
  },
  {
    id: "p9",
    familyId: "alvarez",
    authorId: "sofia",
    kind: "text",
    body: "We won 2-1!!!! Abuela I heard you. The yellow scarf is famous now.",
    createdAt: atDay(22, 18, 3),
  },
  {
    id: "p10",
    familyId: "alvarez",
    authorId: "elena",
    kind: "text",
    body: "I told you about the tomatoes. Did I already tell you about the tomatoes on the south fence.",
    createdAt: atDay(12, 23, 41),
  },
  {
    id: "p11",
    familyId: "alvarez",
    authorId: "miguel",
    kind: "text",
    body: "Ma I got the tomatoes last Sunday. I'll come by tomorrow after work.",
    createdAt: atDay(12, 23, 55),
  },
  {
    id: "p12",
    familyId: "alvarez",
    authorId: "elena",
    kind: "text",
    body: "Where is my purse. I can't find my purse. The tomatoes are ready.",
    createdAt: atDay(9, 1, 12),
  },
  {
    id: "p13",
    familyId: "alvarez",
    authorId: "priya",
    kind: "text",
    body: "Elena, purse is on the hook by the blue door. James is coming home Friday for the digest dinner.",
    createdAt: atDay(9, 7, 20),
  },
  {
    id: "p14",
    familyId: "alvarez",
    authorId: "james",
    kind: "text",
    body: "HackGT this weekend. I'll still be at dinner Friday if the demo doesn't explode. Love you Abuela.",
    createdAt: atDay(6, 21, 8),
  },
  {
    id: "p15",
    familyId: "alvarez",
    authorId: "elena",
    kind: "voice",
    body: "Voice note",
    transcript:
      "The tomatoes. I told you about the tomatoes. Did I tell you about the tomatoes. Where is my purse.",
    voiceSeconds: 22,
    createdAt: atDay(5, 0, 47),
  },
  {
    id: "p16",
    familyId: "alvarez",
    authorId: "sofia",
    kind: "photo",
    body: "Post-practice leftovers. Abuela's salsa still slaps.",
    photoUrl: photoKitchen,
    photoAlt: "Family dinner plates on a table",
    createdAt: atDay(4, 19, 30),
  },
  {
    id: "p17",
    familyId: "alvarez",
    authorId: "elena",
    kind: "text",
    body: "The tomatoes are ready. The tomatoes. I can't find my purse.",
    createdAt: atDay(2, 23, 18),
  },
  {
    id: "p18",
    familyId: "alvarez",
    authorId: "miguel",
    kind: "text",
    body: "Reminder: Saturday 10am soccer tournament at Piedmont. I'll drive Elena.",
    createdAt: atDay(1, 12, 4),
  },
  {
    id: "p19",
    familyId: "alvarez",
    authorId: "elena",
    kind: "status",
    body: "I am tired. The tomatoes. Goodnight.",
    createdAt: atDay(0, 1, 6),
  },
  {
    id: "dm1",
    familyId: "alvarez",
    authorId: "elena",
    threadId: dmThreadId("elena", "miguel"),
    kind: "text",
    body: "Mijo, can you pick up tomatoes Sunday? The red ones on the south fence.",
    createdAt: atDay(3, 10, 15),
  },
  {
    id: "dm2",
    familyId: "alvarez",
    authorId: "miguel",
    threadId: dmThreadId("elena", "miguel"),
    kind: "text",
    body: "Yes Ma. I'll bring Priya too.",
    createdAt: atDay(3, 10, 42),
  },
  {
    id: "dm3",
    familyId: "alvarez",
    authorId: "elena",
    threadId: dmThreadId("elena", "miguel"),
    kind: "text",
    body: "Gracias. Don't forget the chair for my knees.",
    createdAt: atDay(3, 11, 5),
  },
  {
    id: "dm4",
    familyId: "alvarez",
    authorId: "priya",
    threadId: dmThreadId("elena", "priya"),
    kind: "text",
    body: "Elena, your purse is on the hook by the blue door.",
    createdAt: atDay(1, 8, 30),
  },
  {
    id: "dm5",
    familyId: "alvarez",
    authorId: "elena",
    threadId: dmThreadId("elena", "priya"),
    kind: "text",
    body: "Thank you mija. I looked everywhere.",
    createdAt: atDay(1, 8, 55),
  },
  {
    id: "dm6",
    familyId: "alvarez",
    authorId: "james",
    threadId: dmThreadId("james", "sofia"),
    kind: "text",
    body: "You better score tomorrow. I'll be watching from GT.",
    createdAt: atDay(2, 19, 10),
  },
  {
    id: "dm7",
    familyId: "alvarez",
    authorId: "sofia",
    threadId: dmThreadId("james", "sofia"),
    kind: "text",
    body: "Obviously. Tell Abuela to wear the yellow scarf.",
    createdAt: atDay(2, 19, 22),
  },
  {
    id: "r0",
    familyId: "okonkwo",
    authorId: "ruth",
    kind: "text",
    body: "Choir rehearsal ran long but my voice held. I wrote Ada a note about Sunday stew so she does not worry.",
    createdAt: atDay(28, 9, 10),
  },
  {
    id: "r1",
    familyId: "okonkwo",
    authorId: "ruth",
    kind: "text",
    body: "Book club chose Another Country. I am hosting next Thursday so the porch lights will be on early. Ada is bringing jollof.",
    createdAt: atDay(20, 10, 15),
  },
  {
    id: "r2",
    familyId: "okonkwo",
    authorId: "ruth",
    kind: "text",
    body: "Walked the beltline with the girls. My knee behaved. Grateful for a quiet, ordinary morning.",
    createdAt: atDay(14, 8, 40),
  },
  {
    id: "r3",
    familyId: "okonkwo",
    authorId: "ruth",
    kind: "text",
    body: "Made groundnut stew and froze two portions for Sunday. Call me when you land, Kojo.",
    createdAt: atDay(7, 11, 5),
  },
  {
    id: "r4",
    familyId: "okonkwo",
    authorId: "ruth",
    kind: "text",
    body: "Finished the novel. We argued about the ending for an hour and then laughed. I love a house that is loud on purpose.",
    createdAt: atDay(2, 16, 22),
  },
];

export const events: CalendarEvent[] = [
  {
    id: "e1",
    familyId: "alvarez",
    title: "Sofia's soccer tournament",
    startsAt: "2026-09-26T10:00:00-04:00",
    location: "Piedmont Park",
    attendees: ["sofia", "elena", "miguel", "priya"],
    sourceText: "Sarah has her soccer tournament this Saturday at 10 AM",
    createdBy: "miguel",
  },
  {
    id: "e2",
    familyId: "alvarez",
    title: "Friday digest dinner",
    startsAt: "2026-09-25T18:30:00-04:00",
    location: "Miguel & Priya's kitchen",
    attendees: ["elena", "miguel", "priya", "sofia", "james"],
    sourceText: "digest dinner Friday 6:30 at our place",
    createdBy: "priya",
  },
  {
    id: "e3",
    familyId: "alvarez",
    title: "Sunday garden pickup",
    startsAt: "2026-09-27T11:00:00-04:00",
    location: "Elena's south fence",
    attendees: ["elena", "miguel", "priya"],
    sourceText: "Sunday 11 pick up Elena for tomatoes",
    createdBy: "priya",
  },
];
