import { atDay } from "./clock";
import { dmThreadId } from "./chat";
import { alvarezPersonalEvents } from "./demo-personal-calendars";
import type { CalendarEvent, Family, Member, Post, Reminder, WishlistItem } from "./types";

export const families: Family[] = [
  {
    id: "alvarez",
    name: "The Alvarez Circle",
    tagline: "Atlanta · three generations",
    inviteCode: "ALVAREZ42",
    autoAddFamilyCalls: true,
  },
  {
    id: "okonkwo",
    name: "The Okonkwo Circle",
    tagline: "Decatur · three generations",
    inviteCode: "OKONKWO42",
    autoAddFamilyCalls: true,
  },
];

export const members: Member[] = [
  {
    id: "elena",
    familyId: "alvarez",
    name: "Elena Alvarez",
    role: "Abuela",
    age: 78,
    initials: "EA",
    color: "#b45309",
    location: "Grant Park",
    clinicalOptIn: true,
    easyModeDefault: true,
    insurance: { carrierId: "bcbs", policyMemberId: "XYZ123456789", groupId: "GRP-8842" },
  },
  {
    id: "miguel",
    familyId: "alvarez",
    name: "Miguel Alvarez",
    role: "Son",
    age: 52,
    initials: "MA",
    color: "#9a3412",
    location: "Inman Park",
    clinicalOptIn: false,
  },
  {
    id: "priya",
    familyId: "alvarez",
    name: "Priya Alvarez",
    role: "Daughter-in-law",
    age: 48,
    initials: "PA",
    color: "#7c2d12",
    location: "Inman Park",
    clinicalOptIn: false,
  },
  {
    id: "sofia",
    familyId: "alvarez",
    name: "Sofia Alvarez",
    role: "Granddaughter",
    age: 17,
    initials: "SA",
    color: "#c2410c",
    location: "Grady High",
    clinicalOptIn: false,
  },
  {
    id: "james",
    familyId: "alvarez",
    name: "James Alvarez",
    role: "Grandson (GT)",
    age: 21,
    initials: "JA",
    color: "#92400e",
    location: "Georgia Tech",
    clinicalOptIn: false,
  },
  {
    id: "ruth",
    familyId: "okonkwo",
    name: "Ruth Okonkwo",
    role: "Nana",
    age: 74,
    initials: "RO",
    color: "#0f766e",
    location: "Decatur",
    clinicalOptIn: true,
    easyModeDefault: true,
    insurance: { carrierId: "medicare", policyMemberId: "1EG4-TE5-MK72" },
  },
  {
    id: "ada",
    familyId: "okonkwo",
    name: "Ada Okonkwo",
    role: "Daughter",
    age: 50,
    initials: "AO",
    color: "#115e59",
    location: "Decatur",
    clinicalOptIn: false,
  },
  {
    id: "kojo",
    familyId: "okonkwo",
    name: "Kojo Okonkwo",
    role: "Son",
    age: 47,
    initials: "KO",
    color: "#134e4a",
    location: "Denver",
    clinicalOptIn: false,
  },
  {
    id: "chioma",
    familyId: "okonkwo",
    name: "Chioma Okonkwo",
    role: "Granddaughter",
    age: 19,
    initials: "CO",
    color: "#0d9488",
    location: "Emory",
    clinicalOptIn: false,
  },
  {
    id: "emeka",
    familyId: "okonkwo",
    name: "Emeka Okonkwo",
    role: "Son-in-law",
    age: 52,
    initials: "EO",
    color: "#047857",
    location: "Decatur",
    clinicalOptIn: false,
  },
];

const photoGarden =
  "https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=1200&q=80";
const photoSoccer =
  "https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=1200&q=80";
const photoKitchen =
  "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80";
const photoCampus =
  "https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1200&q=80";
const photoJollof =
  "https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?auto=format&fit=crop&w=1200&q=80";

/** Shared demo photos — same URLs as seeded chat posts. */
export const seedPhotos = {
  garden: photoGarden,
  soccer: photoSoccer,
  kitchen: photoKitchen,
  campus: photoCampus,
  jollof: photoJollof,
} as const;

export const posts: Post[] = [
  {
    id: "history-1",
    familyId: "alvarez",
    authorId: "elena",
    kind: "text",
    body: "The neighborhood walk was cool this morning. I stopped by the corner garden and brought home mint for tea.",
    createdAt: atDay(41, 8, 20),
  },
  {
    id: "history-2",
    familyId: "alvarez",
    authorId: "miguel",
    kind: "text",
    body: "Sunday lunch photos are finally in the album. Ma, the one of you and Sofia is my favorite.",
    createdAt: atDay(40, 14, 10),
  },
  {
    id: "history-3",
    familyId: "alvarez",
    authorId: "elena",
    kind: "status",
    body: "Beans are simmering and the porch radio is on. Come by if you are nearby.",
    createdAt: atDay(31, 10, 35),
  },
  {
    id: "history-4",
    familyId: "alvarez",
    authorId: "priya",
    kind: "text",
    body: "I put Sofia's game and the family dinner on the calendar so nobody has to hunt through messages.",
    createdAt: atDay(24, 15, 25),
  },
  {
    id: "history-5",
    familyId: "alvarez",
    authorId: "elena",
    kind: "text",
    body: "Watered the tomatoes before breakfast. The yellow ones are coming in slowly but they taste sweet.",
    createdAt: atDay(18, 8, 5),
  },
  {
    id: "p1",
    familyId: "alvarez",
    authorId: "elena",
    kind: "text",
    body: "I spent the morning thinning the basil so the tomatoes can breathe. Miguel, the red ones on the south fence are ready if you want to come by Sunday. I put a chair in the shade for Priya.",
    createdAt: atDay(38, 9, 12),
  },
  {
    id: "p2",
    familyId: "alvarez",
    authorId: "sofia",
    kind: "photo",
    body: "First varsity start this Saturday. Abuela you better be loud.",
    photoUrl: photoSoccer,
    photoAlt: "Sofia in a soccer jersey on the field",
    createdAt: atDay(36, 16, 40),
  },
  {
    id: "p3",
    familyId: "alvarez",
    authorId: "elena",
    kind: "voice",
    body: "Voice note",
    transcript:
      "Mija I am so proud of you. I will wear the yellow scarf your grandfather liked. Tell coach I still remember how to yell.",
    voiceSeconds: 18,
    channel: "whatsapp",
    rawRetained: false,
    audioMetrics: {
      durationSeconds: 18,
      wordsPerMinute: 96,
      pauseRatio: 0.12,
      averagePauseSeconds: 0.4,
      hesitationRate: 0.02,
    },
    createdAt: atDay(36, 17, 5),
  },
  {
    id: "p4",
    familyId: "alvarez",
    authorId: "james",
    kind: "photo",
    body: "Hackathon fuel. Miss kitchen table energy. Send empanadas via teleport.",
    photoUrl: photoCampus,
    photoAlt: "Georgia Tech campus at dusk",
    createdAt: atDay(34, 22, 10),
  },
  {
    id: "p5",
    familyId: "alvarez",
    authorId: "priya",
    kind: "text",
    body: "Sunday lunch is at our place if the garden run happens. Elena, I'll pick you up at 11 so you don't have to drive.",
    createdAt: atDay(33, 11, 2),
  },
  {
    id: "p6",
    familyId: "alvarez",
    authorId: "elena",
    kind: "text",
    body: "Thank you Priya. I am grateful we still sit down together. I made the salsa the way your mother likes, extra lime.",
    createdAt: atDay(33, 11, 40),
  },
  {
    id: "p7",
    familyId: "alvarez",
    authorId: "miguel",
    kind: "status",
    body: "Dad's old radio is working again. Putting it on the porch for the game.",
    createdAt: atDay(28, 19, 15),
  },
  {
    id: "p8",
    familyId: "alvarez",
    authorId: "elena",
    kind: "photo",
    body: "Harvest day. These tomatoes waited all summer. I want everyone to take a bag.",
    photoUrl: photoGarden,
    photoAlt: "Ripe tomatoes on a vine",
    createdAt: atDay(27, 8, 50),
  },
  {
    id: "p9",
    familyId: "alvarez",
    authorId: "sofia",
    kind: "text",
    body: "We won 2-1!!!! Abuela I heard you. The yellow scarf is famous now.",
    createdAt: atDay(22, 18, 3),
  },
  {
    id: "p10",
    familyId: "alvarez",
    authorId: "elena",
    kind: "text",
    body: "I told you about the tomatoes. Did I already tell you about the tomatoes on the south fence.",
    createdAt: atDay(12, 23, 41),
  },
  {
    id: "p11",
    familyId: "alvarez",
    authorId: "miguel",
    kind: "text",
    body: "Ma I got the tomatoes last Sunday. I'll come by tomorrow after work.",
    createdAt: atDay(12, 23, 55),
  },
  {
    id: "p12",
    familyId: "alvarez",
    authorId: "elena",
    kind: "text",
    body: "Where is my purse. I can't find my purse. The tomatoes are ready.",
    createdAt: atDay(9, 1, 12),
  },
  {
    id: "p13",
    familyId: "alvarez",
    authorId: "priya",
    kind: "text",
    body: "Elena, purse is on the hook by the blue door. James is coming home Friday for the digest dinner.",
    createdAt: atDay(9, 7, 20),
  },
  {
    id: "p14",
    familyId: "alvarez",
    authorId: "james",
    kind: "text",
    body: "HackGT this weekend. I'll still be at dinner Friday if the demo doesn't explode. Love you Abuela.",
    createdAt: atDay(6, 21, 8),
  },
  {
    id: "p15",
    familyId: "alvarez",
    authorId: "elena",
    kind: "voice",
    body: "Voice note",
    transcript:
      "The tomatoes. I told you about the tomatoes. Did I tell you about the tomatoes. Where is my purse.",
    voiceSeconds: 22,
    channel: "whatsapp",
    rawRetained: false,
    audioMetrics: {
      durationSeconds: 22,
      wordsPerMinute: 61,
      pauseRatio: 0.38,
      averagePauseSeconds: 1.4,
      hesitationRate: 0.14,
    },
    createdAt: atDay(5, 0, 47),
  },
  {
    id: "p16",
    familyId: "alvarez",
    authorId: "sofia",
    kind: "photo",
    body: "Post-practice leftovers. Abuela's salsa still slaps.",
    photoUrl: photoKitchen,
    photoAlt: "Family dinner plates on a table",
    createdAt: atDay(4, 19, 30),
  },
  {
    id: "p17",
    familyId: "alvarez",
    authorId: "elena",
    kind: "text",
    body: "The tomatoes are ready. The tomatoes. I can't find my purse.",
    createdAt: atDay(2, 23, 18),
  },
  {
    id: "p18",
    familyId: "alvarez",
    authorId: "miguel",
    kind: "text",
    body: "Reminder: Saturday 10am soccer tournament at Piedmont. I'll drive Elena.",
    createdAt: atDay(1, 12, 4),
  },
  {
    id: "p19",
    familyId: "alvarez",
    authorId: "elena",
    kind: "status",
    body: "I am tired. The tomatoes. Goodnight.",
    createdAt: atDay(0, 1, 6),
  },
  {
    id: "p19b",
    familyId: "alvarez",
    authorId: "elena",
    kind: "text",
    body: "My porch chair fell over and I can't reach it. Anyone nearby?",
    createdAt: atDay(1, 14, 20),
  },
  {
    id: "demo-life-1",
    familyId: "alvarez",
    authorId: "sofia",
    kind: "text",
    body: "Biology midterm today — nervous but I think it went okay. Abuela, wish me luck next time you see this?",
    createdAt: atDay(0, 15, 30),
  },
  {
    id: "demo-life-2",
    familyId: "alvarez",
    authorId: "miguel",
    kind: "text",
    body: "Found Dad's old Mustang photo in the album. Ma, do you remember his first job at the garage in '65?",
    createdAt: atDay(0, 14, 10),
  },
  {
    id: "demo-life-3",
    familyId: "alvarez",
    authorId: "elena",
    kind: "text",
    body: "I still remember your grandfather polishing that car every Sunday. He loved engines more than coffee.",
    createdAt: atDay(0, 13, 45),
  },
  {
    id: "demo-commerce-volcano",
    familyId: "alvarez",
    authorId: "priya",
    kind: "text",
    body: "Sofia has a volcano science project due Friday — we need baking soda, food coloring, and poster board before then.",
    createdAt: atDay(0, 12, 20),
  },
  {
    id: "demo-commerce-tea",
    familyId: "alvarez",
    authorId: "elena",
    kind: "text",
    body: "I ran out of my chamomile tea and the store is too far today. Missing my evening cup.",
    createdAt: atDay(0, 11, 5),
  },
  {
    id: "demo-commerce-care",
    familyId: "alvarez",
    authorId: "elena",
    kind: "text",
    body: "Not feeling well today — stuck at home with a bad cold. Miss everyone.",
    createdAt: atDay(0, 10, 40),
  },
  {
    id: "demo-calendar-1",
    familyId: "alvarez",
    authorId: "priya",
    kind: "text",
    body: "Sofia's tournament is tomorrow at 10 — I pinned it to the calendar so we're all looking at the same plan.",
    createdAt: atDay(0, 16, 40),
  },
  {
    id: "pin-e1",
    familyId: "alvarez",
    authorId: "priya",
    kind: "event_pin",
    body: "📅 Sofia's soccer tournament",
    linkedEventId: "e1",
    createdAt: atDay(0, 16, 41),
    threadId: "group",
  },
  {
    id: "demo-calendar-2",
    familyId: "alvarez",
    authorId: "miguel",
    kind: "text",
    body: "Perfect — I'll pick up Ma at 9:15. Tap Add to My Calendar if you want it on your phone too.",
    createdAt: atDay(0, 16, 48),
  },
  {
    id: "demo-calendar-3",
    familyId: "alvarez",
    authorId: "elena",
    kind: "text",
    body: "I see it. Yellow scarf is ready. Tell Sofia I am loud enough for the whole park.",
    createdAt: atDay(0, 16, 55),
  },
  {
    id: "dm1",
    familyId: "alvarez",
    authorId: "elena",
    threadId: dmThreadId("elena", "miguel"),
    kind: "text",
    body: "Mijo, can you pick up tomatoes Sunday? The red ones on the south fence.",
    createdAt: atDay(3, 10, 15),
  },
  {
    id: "dm2",
    familyId: "alvarez",
    authorId: "miguel",
    threadId: dmThreadId("elena", "miguel"),
    kind: "text",
    body: "Yes Ma. I'll bring Priya too.",
    createdAt: atDay(3, 10, 42),
  },
  {
    id: "dm3",
    familyId: "alvarez",
    authorId: "elena",
    threadId: dmThreadId("elena", "miguel"),
    kind: "text",
    body: "Gracias. Don't forget the chair for my knees.",
    createdAt: atDay(3, 11, 5),
  },
  {
    id: "dm4",
    familyId: "alvarez",
    authorId: "priya",
    threadId: dmThreadId("elena", "priya"),
    kind: "text",
    body: "Elena, your purse is on the hook by the blue door.",
    createdAt: atDay(1, 8, 30),
  },
  {
    id: "dm5",
    familyId: "alvarez",
    authorId: "elena",
    threadId: dmThreadId("elena", "priya"),
    kind: "text",
    body: "Thank you mija. I looked everywhere.",
    createdAt: atDay(1, 8, 55),
  },
  {
    id: "dm6",
    familyId: "alvarez",
    authorId: "james",
    threadId: dmThreadId("james", "sofia"),
    kind: "text",
    body: "You better score tomorrow. I'll be watching from GT.",
    createdAt: atDay(2, 19, 10),
  },
  {
    id: "dm7",
    familyId: "alvarez",
    authorId: "sofia",
    threadId: dmThreadId("james", "sofia"),
    kind: "text",
    body: "Obviously. Tell Abuela to wear the yellow scarf.",
    createdAt: atDay(2, 19, 22),
  },
  {
    id: "r-baseline",
    familyId: "okonkwo",
    authorId: "ruth",
    kind: "voice",
    body: "Voice update",
    transcript: "The garden club met by the library this morning. We planned the autumn beds, shared tea, and made a list for next week.",
    voiceSeconds: 18,
    channel: "whatsapp",
    rawRetained: false,
    audioMetrics: {
      durationSeconds: 18,
      wordsPerMinute: 103,
      pauseRatio: 0.1,
      averagePauseSeconds: 0.35,
      hesitationRate: 0.01,
    },
    createdAt: atDay(35, 9, 25),
  },
  {
    id: "r0",
    familyId: "okonkwo",
    authorId: "ruth",
    kind: "text",
    body: "Choir rehearsal ran long but my voice held. I wrote Ada a note about Sunday stew so she does not worry.",
    createdAt: atDay(28, 9, 10),
  },
  {
    id: "r1",
    familyId: "okonkwo",
    authorId: "ruth",
    kind: "text",
    body: "Book club chose Another Country. I am hosting next Thursday so the porch lights will be on early. Ada is bringing jollof.",
    createdAt: atDay(20, 10, 15),
  },
  {
    id: "r2",
    familyId: "okonkwo",
    authorId: "ruth",
    kind: "text",
    body: "Walked the beltline with the girls. My knee behaved. Quiet morning.",
    createdAt: atDay(14, 8, 40),
  },
  {
    id: "r3",
    familyId: "okonkwo",
    authorId: "ruth",
    kind: "text",
    body: "Made groundnut stew and froze two portions for Sunday. Call me when you land, Kojo.",
    createdAt: atDay(7, 11, 5),
  },
  {
    id: "r4",
    familyId: "okonkwo",
    authorId: "ruth",
    kind: "text",
    body: "Finished the novel. We argued about the ending for an hour, then laughed. I like a house that gets loud on purpose.",
    createdAt: atDay(2, 16, 22),
  },
  {
    id: "r5",
    familyId: "okonkwo",
    authorId: "ada",
    kind: "text",
    body: "Got your note about Sunday stew, Mama. I am bringing jollof and plantains — Emeka is setting up the porch chairs.",
    createdAt: atDay(27, 14, 30),
  },
  {
    id: "r6",
    familyId: "okonkwo",
    authorId: "kojo",
    kind: "text",
    body: "Landed in Denver. Long week but the mountains help. I'll call Sunday after your stew.",
    createdAt: atDay(6, 21, 45),
  },
  {
    id: "r7",
    familyId: "okonkwo",
    authorId: "chioma",
    kind: "photo",
    body: "First week at Emory done. Missing your porch and your stew already.",
    photoUrl: photoCampus,
    photoAlt: "Emory campus in autumn light",
    createdAt: atDay(5, 18, 10),
  },
  {
    id: "r8",
    familyId: "okonkwo",
    authorId: "emeka",
    kind: "text",
    body: "Test run for Thursday book club. Porch lights look good from the street.",
    createdAt: atDay(4, 19, 5),
  },
  {
    id: "r9",
    familyId: "okonkwo",
    authorId: "ada",
    kind: "photo",
    body: "Jollof for Thursday. Mama, save me a seat near the good lamp.",
    photoUrl: photoJollof,
    photoAlt: "A bowl of jollof rice with peppers",
    createdAt: atDay(3, 12, 20),
  },
  {
    id: "r10",
    familyId: "okonkwo",
    authorId: "chioma",
    kind: "text",
    body: "Can someone pick Nana up for the beltline walk Saturday? I have a midterm but I want her to go.",
    createdAt: atDay(1, 9, 15),
  },
  {
    id: "r11",
    familyId: "okonkwo",
    authorId: "emeka",
    kind: "text",
    body: "I'll drive Ruth Saturday morning. Chioma, focus on your exam — we've got the porch covered.",
    createdAt: atDay(1, 10, 2),
  },
  {
    id: "demo-aid-ruth",
    familyId: "okonkwo",
    authorId: "ruth",
    kind: "text",
    body: "The TV remote stopped working again and I can't reach the backup on the shelf. Anyone nearby in Decatur?",
    createdAt: atDay(2, 11, 5),
  },
  {
    id: "demo-life-chioma",
    familyId: "okonkwo",
    authorId: "chioma",
    kind: "text",
    body: "Biology lab practical Friday — nervous but the study group helped. Nana, tell me about your first science fair?",
    createdAt: atDay(0, 16, 15),
  },
  {
    id: "r12",
    familyId: "okonkwo",
    authorId: "kojo",
    kind: "text",
    body: "Book club ending still has me thinking. Wish I could argue with you all in person.",
    createdAt: atDay(0, 15, 40),
  },
  {
    id: "odm1",
    familyId: "okonkwo",
    authorId: "ruth",
    threadId: dmThreadId("ruth", "ada"),
    kind: "text",
    body: "Ada mija, Sunday stew is on. Do not fuss about the drive.",
    createdAt: atDay(8, 9, 20),
  },
  {
    id: "odm2",
    familyId: "okonkwo",
    authorId: "ada",
    threadId: dmThreadId("ruth", "ada"),
    kind: "text",
    body: "Already on it. Emeka is bringing chairs and I'll handle jollof.",
    createdAt: atDay(8, 9, 48),
  },
  {
    id: "odm3",
    familyId: "okonkwo",
    authorId: "ruth",
    threadId: dmThreadId("ruth", "kojo"),
    kind: "text",
    body: "Call me when you land, Kojo. I saved stew for you even from Colorado.",
    createdAt: atDay(7, 16, 10),
  },
  {
    id: "odm4",
    familyId: "okonkwo",
    authorId: "kojo",
    threadId: dmThreadId("ruth", "kojo"),
    kind: "text",
    body: "Just landed. Sunday after stew — promise.",
    createdAt: atDay(6, 22, 5),
  },
  {
    id: "odm5",
    familyId: "okonkwo",
    authorId: "chioma",
    threadId: dmThreadId("chioma", "ada"),
    kind: "text",
    body: "Can you grab Nana for the beltline walk? I have a midterm Saturday.",
    createdAt: atDay(2, 8, 40),
  },
  {
    id: "odm6",
    familyId: "okonkwo",
    authorId: "ada",
    threadId: dmThreadId("chioma", "ada"),
    kind: "text",
    body: "Emeka already said yes. You study — we'll send photos.",
    createdAt: atDay(2, 9, 5),
  },
];

export const reminders: Reminder[] = [
  {
    id: "rem1",
    familyId: "alvarez",
    assigneeId: "miguel",
    text: "Drive Elena to soccer tournament",
    dueAt: "2026-09-26T10:00:00-04:00",
    dueHint: "Saturday 10am",
    sourceText: "Reminder: Saturday 10am soccer tournament at Piedmont. I'll drive Elena.",
    sourcePostId: "p18",
    sourceEventId: "e1",
    createdBy: "miguel",
    createdAt: atDay(1, 12, 4),
    status: "open",
  },
  {
    id: "rem2",
    familyId: "alvarez",
    assigneeId: "miguel",
    text: "Pick up tomatoes from the south fence",
    dueAt: "2026-09-27T17:00:00-04:00",
    dueHint: "Sunday",
    sourceText: "Mijo, can you pick up tomatoes Sunday? The red ones on the south fence.",
    sourcePostId: "dm1",
    sourceEventId: "e3",
    createdBy: "elena",
    createdAt: atDay(3, 10, 15),
    status: "open",
  },
  {
    id: "rem3",
    familyId: "alvarez",
    assigneeId: "james",
    text: "Come home for Friday digest dinner",
    dueAt: "2026-09-25T18:30:00-04:00",
    dueHint: "Friday evening",
    sourceText: "James is coming home Friday for the digest dinner.",
    sourcePostId: "p13",
    sourceEventId: "e2",
    createdBy: "priya",
    createdAt: atDay(9, 7, 20),
    status: "open",
  },
  {
    id: "rem4",
    familyId: "alvarez",
    assigneeId: "james",
    text: "Tell Abuela to wear the yellow scarf",
    dueAt: "2026-09-26T09:00:00-04:00",
    dueHint: "Saturday",
    sourceText: "Obviously. Tell Abuela to wear the yellow scarf.",
    sourcePostId: "dm7",
    createdBy: "sofia",
    createdAt: atDay(2, 19, 22),
    status: "open",
  },
  {
    id: "rem5",
    familyId: "alvarez",
    assigneeId: "priya",
    text: "Bring the yellow scarf and photos to the tournament",
    dueAt: "2026-09-26T10:00:00-04:00",
    dueHint: "Saturday 10am",
    sourceText: "bring the yellow scarf / photos",
    createdBy: "sofia",
    createdAt: atDay(2, 18, 0),
    status: "done",
  },
  {
    id: "rem6",
    familyId: "okonkwo",
    assigneeId: "ada",
    text: "Bring jollof to Thursday book club",
    dueAt: "2026-09-25T17:00:00-04:00",
    dueHint: "Thursday evening",
    sourceText: "Ada is bringing jollof.",
    sourcePostId: "r1",
    sourceEventId: "e4",
    createdBy: "ruth",
    createdAt: atDay(20, 10, 15),
    status: "open",
  },
  {
    id: "rem7",
    familyId: "okonkwo",
    assigneeId: "kojo",
    text: "Call Ruth after landing",
    dueAt: "2026-09-19T21:00:00-04:00",
    dueHint: "Friday evening",
    sourceText: "Call me when you land, Kojo.",
    sourcePostId: "r3",
    createdBy: "ruth",
    createdAt: atDay(7, 11, 5),
    status: "done",
  },
  {
    id: "rem8",
    familyId: "okonkwo",
    assigneeId: "emeka",
    text: "Drive Ruth to beltline walk",
    dueAt: "2026-09-27T09:00:00-04:00",
    dueHint: "Saturday morning",
    sourceText: "I'll drive Ruth Saturday morning.",
    sourcePostId: "r11",
    sourceEventId: "e6",
    createdBy: "emeka",
    createdAt: atDay(1, 10, 2),
    status: "open",
  },
  {
    id: "rem9",
    familyId: "okonkwo",
    assigneeId: "ada",
    text: "Set up porch chairs for book club",
    dueAt: "2026-09-25T16:30:00-04:00",
    dueHint: "Thursday afternoon",
    sourceText: "Emeka is setting up the porch chairs.",
    sourcePostId: "r5",
    createdBy: "ada",
    createdAt: atDay(27, 14, 30),
    status: "open",
  },
];

export const events: CalendarEvent[] = [
  {
    id: "e1",
    familyId: "alvarez",
    title: "Sofia's soccer tournament",
    startsAt: "2026-09-26T10:00:00-04:00",
    endsAt: "2026-09-26T12:30:00-04:00",
    location: "Piedmont Park",
    attendees: ["sofia", "elena", "miguel", "priya"],
    attending: { miguel: "yes", sofia: "yes", elena: "yes", priya: "maybe" },
    supplies: [
      { id: "e1-snacks", item: "Snacks", claimedBy: "miguel" },
      { id: "e1-camp-chairs", item: "Camp chairs" },
      { id: "e1-drinks", item: "Drinks", claimedBy: "elena" },
      { id: "e1-sunscreen", item: "Sunscreen" },
    ],
    sourceText: "Sofia has her soccer tournament this Saturday at 10 AM",
    createdBy: "miguel",
    calendarScope: "family",
  },
  {
    id: "e2",
    familyId: "alvarez",
    title: "Friday digest dinner",
    startsAt: "2026-09-25T18:30:00-04:00",
    endsAt: "2026-09-25T20:30:00-04:00",
    location: "Miguel & Priya's kitchen",
    attendees: ["elena", "miguel", "priya", "sofia", "james"],
    attending: { elena: "yes", miguel: "yes", priya: "yes", sofia: "maybe", james: "no" },
    supplies: [
      { id: "e2-side-dish", item: "Side dish", claimedBy: "priya" },
      { id: "e2-dessert", item: "Dessert" },
      { id: "e2-drinks", item: "Drinks", claimedBy: "james" },
      { id: "e2-bread", item: "Bread" },
    ],
    sourceText: "digest dinner Friday 6:30 at our place",
    createdBy: "priya",
    calendarScope: "family",
  },
  {
    id: "e3",
    familyId: "alvarez",
    title: "Sunday garden pickup",
    startsAt: "2026-09-27T11:00:00-04:00",
    endsAt: "2026-09-27T12:00:00-04:00",
    location: "Elena's south fence",
    attendees: ["elena", "miguel", "priya"],
    attending: { elena: "yes", miguel: "yes" },
    sourceText: "Sunday 11 pick up Elena for tomatoes",
    createdBy: "priya",
    calendarScope: "family",
  },
  {
    id: "e4",
    familyId: "okonkwo",
    title: "Book club at Ruth's porch",
    startsAt: "2026-09-25T18:30:00-04:00",
    endsAt: "2026-09-25T21:00:00-04:00",
    location: "Ruth's porch · Decatur",
    attendees: ["ruth", "ada", "emeka", "chioma"],
    attending: { ruth: "yes", ada: "yes", emeka: "maybe", chioma: "yes" },
    supplies: [
      { id: "e4-food-to-share", item: "Food to share", claimedBy: "ada" },
      { id: "e4-porch-chairs", item: "Porch chairs" },
      { id: "e4-drinks", item: "Drinks" },
      { id: "e4-napkins", item: "Napkins" },
    ],
    sourceText: "hosting next Thursday so the porch lights will be on early",
    createdBy: "ruth",
    calendarScope: "family",
  },
  {
    id: "e5",
    familyId: "okonkwo",
    title: "Sunday stew dinner",
    startsAt: "2026-09-28T13:00:00-04:00",
    endsAt: "2026-09-28T16:00:00-04:00",
    location: "Ruth's kitchen",
    attendees: ["ruth", "ada", "emeka", "kojo", "chioma"],
    attending: { ruth: "yes", ada: "yes", emeka: "yes", chioma: "maybe", kojo: "no" },
    supplies: [
      { id: "e5-side-dish", item: "Side dish" },
      { id: "e5-dessert", item: "Dessert", claimedBy: "chioma" },
      { id: "e5-drinks", item: "Drinks" },
      { id: "e5-bread", item: "Bread", claimedBy: "emeka" },
    ],
    sourceText: "Sunday stew is on",
    createdBy: "ruth",
    calendarScope: "family",
  },
  {
    id: "e6",
    familyId: "okonkwo",
    title: "Beltline walk with the girls",
    startsAt: "2026-09-27T09:30:00-04:00",
    endsAt: "2026-09-27T11:00:00-04:00",
    location: "Atlanta Beltline · Decatur",
    attendees: ["ruth", "emeka"],
    attending: { ruth: "yes", emeka: "yes" },
    sourceText: "Walked the beltline with the girls",
    createdBy: "ruth",
    calendarScope: "family",
  },
  ...alvarezPersonalEvents,
];

export const wishlistItems: WishlistItem[] = [
  {
    id: "wl1",
    familyId: "alvarez",
    forMemberId: "sofia",
    title: "Wireless earbuds",
    note: "For the bus commute — birthday in October",
    estimatedTotal: 49.99,
    createdBy: "sofia",
    createdAt: atDay(5, 14, 20),
    status: "wishlist",
  },
  {
    id: "wl2",
    familyId: "alvarez",
    forMemberId: "elena",
    title: "Cozy throw blanket",
    note: "Something warm for the living room couch",
    estimatedTotal: 34.99,
    createdBy: "priya",
    createdAt: atDay(4, 9, 10),
    status: "wishlist",
  },
  {
    id: "wl3",
    familyId: "alvarez",
    forMemberId: "sofia",
    title: "Volcano science project supplies",
    note: "Baking soda, food coloring, poster board",
    kind: "supply",
    items: [
      { name: "Baking soda", quantity: 1 },
      { name: "Food coloring", quantity: 1 },
      { name: "Poster board", quantity: 1 },
    ],
    estimatedTotal: 18.5,
    sourcePostId: "demo-commerce-volcano",
    createdBy: "priya",
    createdAt: atDay(0, 12, 25),
    status: "wishlist",
  },
  {
    id: "wl4",
    familyId: "alvarez",
    forMemberId: "elena",
    title: "Chamomile tea (3 boxes)",
    note: "Her usual brand — evening ritual",
    kind: "supply",
    items: [{ name: "Chamomile tea", quantity: 3 }],
    estimatedTotal: 12.99,
    sourcePostId: "demo-commerce-tea",
    createdBy: "miguel",
    createdAt: atDay(0, 11, 30),
    status: "ordered",
    orderedBy: "miguel",
    orderedAt: atDay(0, 14, 5),
  },
  {
    id: "wl5",
    familyId: "alvarez",
    forMemberId: "james",
    title: "GT hoodie (medium)",
    note: "Navy or gold",
    estimatedTotal: 54.0,
    createdBy: "james",
    createdAt: atDay(8, 16, 0),
    status: "purchased",
    orderedBy: "priya",
    orderedAt: atDay(7, 10, 0),
  },
];
