import type { LifeStoryPrompt } from "./types";

/** Curated demo copy for Social Good chat extensions (judges / sample mode). */

export type SocialDemoFeature = "mutual_aid" | "life_story" | "check_in" | "commerce";

export type SocialDemoExample = {
  id: string;
  feature: SocialDemoFeature;
  title: string;
  blurb: string;
  /** Already visible in seeded group chat — scroll to find it. */
  inSeed?: boolean;
  seedHint?: string;
  /** Prefill the composer when tapped. */
  tryMessage?: string;
  /** Suggested “Posting as” member id in sample families. */
  postAs?: string;
  lookFor: string;
  /** Switch posting-as to see this (e.g. safe check-in hides for the inactive elder). */
  viewAs?: string;
};

export const SOCIAL_DEMO_EXAMPLES: SocialDemoExample[] = [
  {
    id: "aid-porch",
    feature: "mutual_aid",
    title: "Mutual aid — porch chair",
    blurb: "Elena posted a local favor the family can't do from far away.",
    inSeed: true,
    seedHint: "Scroll to Elena: “My porch chair fell over…”",
    lookFor: "Forward local help request chip → Grant Park Neighbors or GT Service Club",
    viewAs: "miguel",
  },
  {
    id: "aid-yarn",
    feature: "mutual_aid",
    title: "Mutual aid — try typing",
    blurb: "Lightweight detection while you compose.",
    tryMessage: "I ran out of yarn and the store bags are too heavy to carry alone.",
    postAs: "elena",
    lookFor: "Local assistance banner above the composer while typing",
    viewAs: "miguel",
  },
  {
    id: "aid-tv",
    feature: "mutual_aid",
    title: "Mutual aid — Okonkwo circle",
    blurb: "Switch circles in Settings to Decatur.",
    inSeed: true,
    seedHint: "Ruth: “TV remote… can't reach the backup on the shelf”",
    lookFor: "Decatur Mutual Aid or Emory Student Volunteers",
    viewAs: "ada",
  },
  {
    id: "story-exam",
    feature: "life_story",
    title: "Life story — biology exam",
    blurb: "Prompts are generated by Meta Muse 1.3 from recent chat.",
    inSeed: true,
    seedHint: "Sofia posted about her biology midterm today",
    lookFor: "Conversation starters card — “Use in chat” prefills a warm question",
    viewAs: "elena",
  },
  {
    id: "story-cars",
    feature: "life_story",
    title: "Life story — first job / cars",
    blurb: "Grandpa's garage came up in the thread.",
    inSeed: true,
    seedHint: "Miguel's Mustang photo + Elena's memory reply",
    lookFor: "Starter for Sofia: ask Abuela about his first job in '65",
    viewAs: "sofia",
  },
  {
    id: "story-try",
    feature: "life_story",
    title: "Life story — try typing",
    blurb: "Send a memory cue and watch prompts refresh.",
    tryMessage: "Remember when we all piled into the station wagon for the lake every August?",
    postAs: "elena",
    lookFor: "Conversation starters update after send (refresh or wait ~4s)",
    viewAs: "sofia",
  },
  {
    id: "checkin-elena",
    feature: "check_in",
    title: "Safe check-in — Elena",
    blurb: "Passive ping when an elder goes quiet — no invasive tracking.",
    inSeed: true,
    seedHint: "Elena's last message was ~19 hours ago in sample time",
    lookFor: "Hestia missed Elena today → ☀️ Send sunny emoji",
    viewAs: "miguel",
  },
  {
    id: "checkin-alert",
    feature: "check_in",
    title: "Safe check-in — alert stage",
    blurb: "If the ping goes unacknowledged, the primary contact gets a nudge.",
    inSeed: true,
    seedHint: "Pre-seeded in sample mode: prompt sent 14+ hours ago",
    lookFor: "Amber Safe check-in banner for Miguel",
    viewAs: "miguel",
  },
  {
    id: "checkin-ruth",
    feature: "check_in",
    title: "Safe check-in — Ruth (Okonkwo)",
    blurb: "Works in any circle with an elder on Larger text.",
    inSeed: true,
    seedHint: "Switch to Okonkwo · Ruth quiet ~2 days in sample time",
    lookFor: "Same ping flow for Ruth when posting as Ada",
    viewAs: "ada",
  },
  {
    id: "checkin-mood",
    feature: "check_in",
    title: "Message check-in — low mood",
    blurb: "Recognizes mood, anxiety, sleep, and more — not just memory slips.",
    tryMessage: "I have been feeling hopeless and I cannot sleep at all.",
    postAs: "elena",
    lookFor: "Amber gentle check-in chip with Low mood · Draft a warm reply",
    viewAs: "miguel",
  },
  {
    id: "checkin-bipolar",
    feature: "check_in",
    title: "Message check-in — bipolar",
    blurb: "Named disorders like bipolar, PTSD, OCD, ADHD, and depression — not a diagnosis.",
    tryMessage: "My bipolar is acting up and I have not slept in three days.",
    postAs: "elena",
    lookFor: "Bipolar label under Elena's message · Draft a warm reply",
    viewAs: "miguel",
  },
  {
    id: "checkin-cognitive",
    feature: "check_in",
    title: "Message check-in — cognitive change",
    blurb: "Still catches confusion and memory language in chat.",
    tryMessage: "I keep forgetting where I put my glasses and I feel lost.",
    postAs: "elena",
    lookFor: "Cognitive change label under Elena's message",
    viewAs: "sofia",
  },
  {
    id: "commerce-volcano",
    feature: "commerce",
    title: "Auto-supply — school project",
    blurb: "Priya mentioned Sofia's volcano project supplies.",
    inSeed: true,
    seedHint: "Scroll to Priya: “Sofia has a volcano science project due Friday…”",
    lookFor: "Shopping suggestion card → Order & Deliver to Sofia",
    viewAs: "miguel",
  },
  {
    id: "commerce-tea",
    feature: "commerce",
    title: "Auto-supply — hobby restock",
    blurb: "Elena ran out of her favorite tea.",
    inSeed: true,
    seedHint: "Elena: “I ran out of my chamomile tea…”",
    lookFor: "Supply restock card with estimated total",
    viewAs: "miguel",
  },
  {
    id: "commerce-bring",
    feature: "commerce",
    title: "Shopping — bring list",
    blurb: "When someone offers to bring food, Hearth suggests ordering instead.",
    inSeed: true,
    seedHint: "Emeka: “Got your note about Sunday stew… bringing jollof and plantains”",
    lookFor: "Shopping suggestion card → Order Jollof instead",
    viewAs: "miguel",
  },
  {
    id: "commerce-try",
    feature: "commerce",
    title: "Auto-supply — try typing",
    blurb: "Compose a supply need and see the card appear.",
    tryMessage: "James has a diorama due next week — we need poster board and glue sticks.",
    postAs: "priya",
    lookFor: "Draft commerce card above the composer",
    viewAs: "miguel",
  },
];

/** Fixed conversation starters for sample mode — no Groq round-trip. */
export function demoLifeStoryPrompts(familyId: string): LifeStoryPrompt[] {
  if (familyId === "okonkwo") {
    return [
      {
        id: "demo-lp-ok-1",
        forMemberId: "chioma",
        forMemberName: "Chioma",
        aboutMemberId: "ruth",
        aboutMemberName: "Nana",
        prompt: "You asked about Nana's first science fair — follow up while she's on your mind!",
        reason: "Chioma mentioned a lab practical and Nana's stories.",
      },
      {
        id: "demo-lp-ok-2",
        forMemberId: "ada",
        forMemberName: "Ada",
        aboutMemberId: "ruth",
        aboutMemberName: "Ruth",
        prompt: "Ruth posted about the TV remote — check in and ask if someone stopped by.",
        reason: "Recent help request in chat.",
      },
      {
        id: "demo-lp-ok-3",
        forMemberId: "chioma",
        forMemberName: "Chioma",
        aboutMemberId: "ruth",
        aboutMemberName: "Nana",
        prompt: "Ask Nana who argued loudest at book club — she said the ending still has her thinking.",
        reason: "Book club came up in chat.",
      },
      {
        id: "demo-lp-ok-4",
        forMemberId: "kojo",
        forMemberName: "Kojo",
        aboutMemberId: "ruth",
        aboutMemberName: "Ruth",
        prompt: "You landed in Denver — promise Sunday stew and ask what Ruth saved for you.",
        reason: "Kojo posted about the long week and coming home.",
      },
      {
        id: "demo-lp-ok-5",
        forMemberId: "ada",
        forMemberName: "Ada",
        aboutMemberId: "chioma",
        aboutMemberName: "Chioma",
        prompt: "Chioma has a midterm Saturday — tell her to focus; you'll send beltline walk photos.",
        reason: "Family coordinating around school and walks.",
      },
      {
        id: "demo-lp-ok-6",
        forMemberId: "emeka",
        forMemberName: "Emeka",
        aboutMemberId: "ruth",
        aboutMemberName: "Ruth",
        prompt: "Ask Ruth if the porch lights are ready for Thursday book club — offer to set chairs early.",
        reason: "Ruth is hosting on the porch this week.",
      },
      {
        id: "demo-lp-ok-7",
        forMemberId: "chioma",
        forMemberName: "Chioma",
        aboutMemberId: "ruth",
        aboutMemberName: "Nana",
        prompt: "Tell Nana you miss her stew already — ask for one tip before your next lab week.",
        reason: "Chioma posted about missing the porch.",
      },
    ];
  }

  return [
    {
      id: "demo-lp-1",
      forMemberId: "sofia",
      forMemberName: "Sofia",
      aboutMemberId: "elena",
      aboutMemberName: "Abuela",
      prompt: "Ask Abuela about Abuelo's first job in '65 — he loved those cars!",
      reason: "Recent chat mentions cars and the garage.",
    },
    {
      id: "demo-lp-2",
      forMemberId: "elena",
      forMemberName: "Elena",
      aboutMemberId: "sofia",
      aboutMemberName: "Sofia",
      prompt: "Sofia posted about her biology midterm — ask how it went!",
      reason: "School came up in chat.",
    },
    {
      id: "demo-lp-3",
      forMemberId: "sofia",
      forMemberName: "Sofia",
      aboutMemberId: "miguel",
      aboutMemberName: "Abuelo",
      prompt: "Ask Abuelo to tell the longer story behind the Mustang photo.",
      reason: "Memory theme in recent posts.",
    },
    {
      id: "demo-lp-4",
      forMemberId: "james",
      forMemberName: "James",
      aboutMemberId: "elena",
      aboutMemberName: "Abuela",
      prompt: "Tell Abuela HackGT went okay — ask what she would pack you if empanadas could teleport.",
      reason: "James posted from campus about missing home.",
    },
    {
      id: "demo-lp-5",
      forMemberId: "miguel",
      forMemberName: "Miguel",
      aboutMemberId: "elena",
      aboutMemberName: "Elena",
      prompt: "Confirm Sunday tomato pickup with Ma — mention Priya is coming too.",
      reason: "Garden harvest and Sunday lunch are on the calendar.",
    },
    {
      id: "demo-lp-6",
      forMemberId: "priya",
      forMemberName: "Priya",
      aboutMemberId: "elena",
      aboutMemberName: "Elena",
      prompt: "Ask Elena for the salsa recipe with extra lime — Sofia asked after the game.",
      reason: "Cooking and Sunday dinner came up in chat.",
    },
    {
      id: "demo-lp-7",
      forMemberId: "elena",
      forMemberName: "Elena",
      aboutMemberId: "sofia",
      aboutMemberName: "Sofia",
      prompt: "Sofia won 2-1 — tell her the yellow scarf is famous now and you heard her from the porch.",
      reason: "Soccer victory in recent posts.",
    },
    {
      id: "demo-lp-8",
      forMemberId: "james",
      forMemberName: "James",
      aboutMemberId: "miguel",
      aboutMemberName: "Abuelo",
      prompt: "Ask Abuelo if Dad's porch radio is still working — Elena said it's on for the game.",
      reason: "Miguel fixed the old radio for game day.",
    },
    {
      id: "demo-lp-9",
      forMemberId: "sofia",
      forMemberName: "Sofia",
      aboutMemberId: "elena",
      aboutMemberName: "Abuela",
      prompt: "Thank Abuela for the voice note before your game — ask what she yelled at your age.",
      reason: "Elena sent a proud voice note about the yellow scarf.",
    },
    {
      id: "demo-lp-10",
      forMemberId: "miguel",
      forMemberName: "Miguel",
      aboutMemberId: "elena",
      aboutMemberName: "Elena",
      prompt: "Ma keeps mentioning the tomatoes — send a quick photo from the south fence when you visit.",
      reason: "Tomato harvest has been a running thread.",
    },
  ];
}

export function socialDemoExamplesForFamily(familyId: string): SocialDemoExample[] {
  if (familyId === "okonkwo") {
    return SOCIAL_DEMO_EXAMPLES.filter((e) => e.id === "aid-tv" || e.id === "checkin-ruth" || e.feature === "life_story");
  }
  return SOCIAL_DEMO_EXAMPLES.filter((e) => !e.id.startsWith("aid-tv") && e.id !== "checkin-ruth");
}

export const SOCIAL_DEMO_FEATURE_LABELS: Record<SocialDemoFeature, string> = {
  mutual_aid: "Mutual aid",
  life_story: "Life story prompts",
  check_in: "Safe check-in",
  commerce: "Shopping suggestions",
};
